# Generated by Django 3.0.5 on 2020-04-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='purchasedate',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='purchaseprice',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='serialnumber',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='room_name',
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
