# Generated by Django 3.0.5 on 2020-04-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homi', '0002_auto_20200416_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
    ]
